version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install -r requirements.txt
  build:
    commands:
      - python -m pytest --junitxml=testreport/unittests

reports:
  pytest_reports:
    files:
      - unittests
    base-directory: testreport
    file-format: JUNITXML
