version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "trading-bot-sam-stack-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1t9y9cfgi8rvb"
s3_prefix = "trading-bot-sam-stack-prod"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
