AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Metadata:
  AWS::ServerlessRepo::Application:
    Name: trading-bot
    Description: Trading Bot
    Author: jbmerville
    ReadmeUrl: README.md
    Labels: ["tests"]
    HomePageUrl: https://github.com/jbmerville/trading-bot
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/jbmerville/trading-bot

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    # Your CORS hosts need to be in this format - note the two layers of quotes.
    Cors: "'*'"

# Our Python callback
Resources:
  YourFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      Events:
        Callback:
          Type: Api
          Properties:
            Path: /yourcallback
            Method: get
            RestApiId:
              Ref: YourAPIGateway

  # Our callback API
  YourAPIGateway:
    Type: AWS::Serverless::Api
    DependsOn: YourFunction
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: 2.0
        info:
          version: "1.0"
          title: "A nice title"
        basePath: /prod
        schemes:
          - "https"
        paths:
          /callback:
            get:
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  # You need to build up the ARN with this pattern - you can't just use a !Ref or !GetAtt AFAIK.
                  Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${YourFunction.Arn}/invocations
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
